# Generated by Django 4.2.4 on 2023-08-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('researcher', models.CharField(max_length=20)),
                ('pv1', models.CharField(max_length=20)),
                ('pv2', models.CharField(max_length=20)),
                ('pv3', models.CharField(max_length=20)),
                ('pn1', models.CharField(max_length=20)),
                ('pn4', models.CharField(max_length=20)),
            ],
        ),
    ]
