# Generated by Django 4.2.4 on 2023-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poverty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('familysize', models.IntegerField()),
                ('old', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('kid', models.IntegerField()),
                ('pline', models.FloatField()),
            ],
            options={
                'unique_together': {('year', 'old', 'adult', 'kid')},
            },
        ),
    ]
