# Generated by Django 4.2.4 on 2023-10-10 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rise', '0005_alter_interview_object_type_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='financial_supporter_type',
            new_name='partner_support_status',
        ),
    ]
