# Generated by Django 4.2.4 on 2023-10-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rise', '0006_rename_financial_supporter_type_interview_partner_support_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='housing_comments',
            new_name='housing_comments_1',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='move_date',
            new_name='move_date_1',
        ),
        migrations.AddField(
            model_name='interview',
            name='housing_comments_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='housing_comments_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='housing_comments_4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='housing_comments_5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='move_date_2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='move_date_3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='move_date_4',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='move_date_5',
            field=models.DateField(null=True),
        ),
    ]
