# Generated by Django 4.2.4 on 2023-10-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rise', '0007_rename_housing_comments_interview_housing_comments_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='financial_familiy_adult',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interview',
            name='financial_familiy_child',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interview',
            name='household_adult',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interview',
            name='household_child',
            field=models.IntegerField(default=0),
        ),
    ]
