# Generated by Django 4.2.4 on 2023-10-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rise', '0008_alter_interview_financial_familiy_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='household_member_changes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pv1_q1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pv1_q2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pv1_q3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pv1_q4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pv1_q5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pv1_q6',
            field=models.TextField(null=True),
        ),
    ]
