# Generated by Django 4.2.4 on 2023-10-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rise', '0009_interview_household_member_changes_interview_pv1_q1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='household_member_changes',
            new_name='household_member_changes_1',
        ),
        migrations.AddField(
            model_name='interview',
            name='household_member_changes_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='household_member_changes_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='household_member_changes_4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='household_member_changes_5',
            field=models.TextField(null=True),
        ),
    ]
