# Generated by Django 4.2.4 on 2023-10-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rise', '0010_rename_household_member_changes_interview_household_member_changes_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='household_member_changes_1',
            new_name='household_member_changes_comments_1',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='household_member_changes_2',
            new_name='household_member_changes_comments_2',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='household_member_changes_3',
            new_name='household_member_changes_comments_3',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='household_member_changes_4',
            new_name='household_member_changes_comments_4',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='household_member_changes_5',
            new_name='household_member_changes_comments_5',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='pv1_q1',
            new_name='pn1_q1',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='pv1_q2',
            new_name='pn1_q2',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='pv1_q3',
            new_name='pn1_q3',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='pv1_q4',
            new_name='pn1_q4',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='pv1_q5',
            new_name='pn1_q5',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='pv1_q6',
            new_name='pn1_q6',
        ),
        migrations.AddField(
            model_name='interview',
            name='household_member_changes_date_1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='household_member_changes_date_2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='household_member_changes_date_3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='household_member_changes_date_4',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='household_member_changes_date_5',
            field=models.DateField(null=True),
        ),
    ]
